### ISSUE TITLE
Needs error message

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-NECN-Succession#33]
When an ecoregion exists on the map, but not the succession input file, should throw an error.

See: 

Running NECN Succession ...
2018-02-14 15:54:17,661 - Internal error occurred within the program:
2018-02-14 15:54:17,662 -   Object reference not set to an instance of an object.
2018-02-14 15:54:17,663 - 
2018-02-14 15:54:17,663 - Stack trace:
2018-02-14 15:54:17,667 -    at Edu.Wisc.Forest.Flel.Util.Percentage.op_Implicit(Percentage percentage)
   at Landis.Extension.Succession.NetEcosystemCN.PlugIn.ComputeShade(ActiveSite site)
   at Landis.Library.Succession.ExtensionBase.ComputeShade(IEnumerable`1 sites)
   at Landis.Library.Succession.ExtensionBase.RunReproductionFirst()
   at Landis.Extension.Succession.NetEcosystemCN.PlugIn.Run()
   at Landis.Model.Run(ExtensionMain extension)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by rmscheller** [comment]
Now that NECN is ecoregion free, should not be an issue.
